name: kasir_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  # ðŸ”¥ Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

  # ðŸ“± Fitur tambahan
  mobile_scanner: ^4.0.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  pdf: ^3.8.4
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.3
  esc_pos_bluetooth: ^0.4.1
  esc_pos_utils: ^1.1.0
  share_plus: ^10.0.2
  file_selector: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - image/nira_posbaru.png
